const products = [
    {
        id: 1,
        name: "Syltherine",
        info: "Stylish cafe chair",
        poster: "../images/products/syltherine.png",
        price: 2500000,
        old_price: 3500000,
    },
    {
        id: 2,
        name: "Leviosa",
        info: "Stylish cafe chair",
        poster: "../images/products/leviosa.png",
        price: 2500000,
        old_price: '',
    },
    {
        id: 3,
        name: "Lolito",
        info: "Luxury big sofa",
        poster: "../images/products/lolito.png",
        price: 700000,
        old_price: 14000000,
    },
    {
        id: 4,
        name: "Respira",
        info: "Minimalist fan",
        poster: "../images/products/respira.png",
        price: 500000,
        old_price: '',
    },
    {
        id: 5,
        name: "Grifo",
        info: "Night lamp",
        poster: "../images/products/grifo.png",
        price: 1500000,
        old_price: 3500000,
    },
    {
        id: 6,
        name: "Muggo",
        info: "Small mug",
        poster: "../images/products/muggo.png",
        price: 150000,
        old_price: '',
    },
    {
        id: 7,
        name: "Pingky",
        info: "Cute bed set",
        poster: "../images/products/pingky.png",
        price: 7000000,
        old_price: 14000000,
    },
    {
        id: 8,
        name: "Potty",
        info: "Minimalist flower pot",
        poster: "../images/products/potty.png",
        price: 500000,
        old_price: '',
    },
]